### ISSUE TITLE
rl.distribution, etc. 

### ISSUE THREAD

**Issue by tylerqblack** [TikhonJelvis/RL-book#152]
I keep seeing the command:

import rl.distribution

But I can't find which package this command is from. Is it from Keras-rl or gym?

**Comment by TikhonJelvis** [comment]
That's code that we wrote specifically for the book. It's in the [rl][1] directory in this repo.

[1]: https://github.com/TikhonJelvis/RL-book/tree/master/rl

**Comment by tylerqblack** [comment]
That makes much more sense now, thank you!
