### ISSUE TITLE
requirements.txt issues on Windows

### ISSUE THREAD

**Issue by tylerqblack** [TikhonJelvis/RL-book#153]
I had a few issues with requirements.txt dependencies. I ran into installation errors with:

pandas == 1.0.3 --> switched it to 1.3.0 and it worked fine. 
scipy == 1.4.1 --> switched to 1.7.0 and it worked. 

requests 2.24.0 then conflicted with urllib3 == 1.26.5, as it depended on earlier versions. Switched to urllib 1.21.1 to resolve. Ran into some more build errors down the line. 

For context, I'm on running in an anaconda environment on a Windows OS which could be the problem. The requirements may run correctly on a Linux VM.

**Comment by TikhonJelvis** [comment]
Thanks for the notes! I'll try updating the dependencies and testing on my Linux setup, but I won't have time to test them on Windows or with anaconda.

What version of Python are you using? I thought our code needed 3.8 or higher, although it looks like the tests are passing with Python 3.7 on Travis, so I'm probably wrong about that :P. Ideally I should probably a) move to GitHub actions and b) test on multiple versions of Python, but realistically that will have to wait until the book is closer to done.

**Comment by tylerqblack** [comment]
Sure! I think your book is an awesome resource and I appreciate you making it open source. 

I have the environment specified to python=3.9. I was trying to get set up on my MacBook but some packages aren't porting to the m1 chip so I ended up trying it on Windows. To be completely honest I don't know how to use the travis.yml file, I just kind of try to cobble things together to get the code working. I've got files from ch.2 running now with a few modifications.

**Comment by TikhonJelvis** [comment]
Sounds good. The `travis.yml` file is what configures the way we run automated tests on every PR in GitHub—it's not meant for local use.

For working on Windows, either anaconda or something like [pyenv-win] + Pip seem like the best choices to manage a Python development environment, but I have basically no experience developing on Windows so please take my advice with a grain of salt :).

[pyenv-win]: https://github.com/pyenv-win/pyenv-win

**Comment by TikhonJelvis** [comment]
Okay, I bumped those packages (see PR #154) and tested the results on my Linux machine. Would you mind trying it out? I don't have Windows set up to test myself.

Thanks!

**Comment by tylerqblack** [comment]
Sure! I just gave it a try and it failed trying to build wheels for matplotlib and pyzmq. I installed Cython and tried again, still failed. I think the workaround is for Windows users to just install mpl and pyzmq separately. It's probably due to MSVC compiler differences with what I'm guessing would be a GNU compiler on Linux.

**Comment by TikhonJelvis** [comment]
Okay, thanks for the update. Don't think I can fix the problem right now, so I'm going to close this issue. I'll update the title to mention Windows explicitly so that is easier for other people to find in the future.
