### ISSUE TITLE
typing or rl.distribution?

### ISSUE THREAD

**Issue by Peymankor** [TikhonJelvis/RL-book#206]
Thanks for the book - I am enjoying reading the book and its "modular" python codes.

I assume that in Chapter "Markov Processes" (sec:mrp-chapter), in the python code above the "Simple Inventory Example" (page 72 of book pdf), the 

`from typing import FiniteDistribution, Categorical` 
needs to be changed to 
`from rl.distribution import FiniteDistribution, Categorical`

**Comment by coverdrive** [comment]
fixed
